name: flutter-build-android
description: Builds an apk or appbundle
branding:
  icon: box
  color: green
inputs:
  working-directory:
    description: The root directory of the flutter app within this repository
    default: ./
  build-cmd:
    description: The full build command, can be used to add arguments
    default: flutter build apk --release
  keystore-base64:
    description: "keystore with which to sign the app"
    required: true
  keystore-password:
    description: "The password for the playstore key used to sign the app"
    required: true

runs:
  using: "composite"
  steps:
    - name: Check java found
      id: check_java
      shell: bash
      run: |
        if java --version 2>&1 | grep -q "17"; then
            echo "installed=true" >> "$GITHUB_OUTPUT"
        else
            echo "installed=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Install java
      if: steps.check_java.outputs.installed == 'false'
      uses: actions/setup-java@v3
      with:
        distribution: "zulu"
        java-version: "17.x"

    - name: Check flutter found
      id: check_flutter
      shell: bash
      run: |
        if flutter --version; then
            echo "installed=true" >> "$GITHUB_OUTPUT"
        else
            echo "installed=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Setup flutter
      if: steps.check_flutter.outputs.installed == 'false'
      uses: subosito/flutter-action@v2
      with:
        channel: "stable"
        flutter-version: '3.27.1'
        cache: true

    - run: flutter doctor -v
      shell: bash


    - name: Flutter clean
      run: flutter clean
      shell: bash

    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1.5.0
      with:
        ndk-version: r26d

    - name: Decode keystore and create jks and properties file for signing the app
      shell: bash
      run: |
        echo "$KEYSTORE" | base64 --decode > app/keystore.jks
        echo "storeFile=keystore.jks" >> key.properties
        echo "keyAlias=datadash-wallet" >> key.properties
        echo "storePassword=$KEYSTORE_PASSWORD" >> key.properties
        echo "keyPassword=$KEYSTORE_PASSWORD" >> key.properties
      env:
        KEYSTORE: ${{ inputs.keystore-base64 }}
        KEYSTORE_PASSWORD: ${{ inputs.keystore-password }}
      working-directory: ${{ inputs.working-directory }}/android

    - name: Build
      run: ${{ inputs.build-cmd }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
